package controller;

public enum MenusName {
    //login
    LOGIN_MENU,
    SECURITY_QUESTION_CONFIRM_MENU,
    FORGOT_PASSWORD_MENU,
    SECURITY_QUESTION_CHOOSE_MENU,
    REGISTER_MENU,
    CAPTCHA_MENU,
    //profile
    PROFILE_MENU,
    CHANGE_PASSWORD_MENU,
    LEADER_BOARD_MENU,
    CHOOSE_AVATAR_MENU,




    MAIN_MENU,
    RESET_PASSWORD_MENU,
    GAME_MENU,
    CREATE_MAP_MENU,
    SHOW_MAP_MENU,
    SHOP_MENU,
    TRADE_MENU
}
