package controller;

public enum MenusName {
    //login
    LOGIN_MENU,
    SECURITY_QUESTION_CONFIRM_MENU,
    FORGOT_PASSWORD_MENU,
    SECURITY_QUESTION_CHOOSE_MENU,
    REGISTER_MENU,



    MAIN_MENU,
    PROFILE_MENU,
    RESET_PASSWORD_MENU,
    GAME_MENU,
    CREATE_MAP_MENU,
    SHOW_MAP_MENU,
    SHOP_MENU,
    TRADE_MENU
}
